all:
	pdflatex broom
##pdflatex broom
##pdflatex -shell-escape broom
##pdflatex -shell-escape broom
##bibtex broom
##bibtex broom
##pdflatex -shell-escape broom
##bibtex broom
##pdflatex -shell-escape broom

fast:
	pdflatex broom
clean:
	rm *.log *.aux *.bbl
